AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: YouTube Live to Facebook Stories - Serverless Application AWS Resources

Globals:
  Function:
    Runtime: python3.12
    Timeout: 120
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: ytlive2fbstories
        LOG_LEVEL: INFO

Resources:
  # CloudWatch Logs for API Gateway
  ApiGatewayLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/ytlive2fbstories-apig
      RetentionInDays: 90

  # CloudWatch Logs for Lambda Function to Post Stories
  StoriesLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ytlive2fbstories-lambda-stories
      RetentionInDays: 90

  # CloudWatch Logs for Lambda Function to Update Facebook Token
  FBTokenLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ytlive2fbstories-lambda-fbtoken
      RetentionInDays: 90

  # CloudWatch Logs for Lambda Function to Renew Google PubSubHubbub Subscription
  WebSubLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ytlive2fbstories-lambda-websub
      RetentionInDays: 90

  # DynamoDB Table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ytlive2fbstories-dynamodb
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: video_id
          AttributeType: S
      KeySchema:
        - AttributeName: video_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Lambda Function to Post Stories
  StoriesLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ytlive2fbstories-lambda-stories
      CodeUri: ../lambda/stories/
      Handler: app.lambda_handler
      Description: Process YouTube Live Stream Notifications and Post to Facebook Stories
      Policies: # TODO: 最小特権の原則に従ったIAMポリシーを設定する
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - SSMParameterReadPolicy:
            ParameterName: /ytlive2fbstories/*
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId: !Ref ApiGateway
      LoggingConfig:
        LogGroup: !Ref StoriesLambdaFunctionLogs

  # Lambda Function for Facebook Token
  FBTokenLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ytlive2fbstories-lambda-fbtoken
      CodeUri: ../lambda/fbtoken/
      Handler: app.lambda_handler
      Description: Update Facebook Long-Lived Access Token
      Policies: # TODO: 最小特権の原則に従ったIAMポリシーを設定する
        - SSMParameterReadPolicy:
            ParameterName: /ytlive2fbstories/facebook/*
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlive2fbstories/facebook/*"
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(57 days)
            Name: ytlive2fbstories-ebrule-fbtoken
            Description: Schedule to Refresh Facebook Token Before It Expires
      LoggingConfig:
        LogGroup: !Ref FBTokenLambdaFunctionLogs

  # Lambda Function for Google PubSubHubbub Subscription
  WebSubLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ytlive2fbstories-lambda-websub
      CodeUri: ../lambda/websub/
      Handler: app.lambda_handler
      Description: Renew Google PubSubHubbub Subscription
      Policies: # TODO: 最小特権の原則に従ったIAMポリシーを設定する
        - SSMParameterReadPolicy:
            ParameterName: /ytlive2fbstories/youtube/*
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlive2fbstories/youtube/*"
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
            Name: ytlive2fbstories-ebrule-websub
            Description: Schedule to Refresh WebSub Subscription Before It Expires
      LoggingConfig:
        LogGroup: !Ref WebSubLambdaFunctionLogs

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ytlive2fbstories-apig
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        DefaultAuthorizer: NONE
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogs.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "routeKey":"$context.routeKey", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength" }'

  # Systems Manager Parameter for Facebook Page ID
  FacebookPageIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlive2fbstories/facebook/page_id
      Type: String
      Value: default-page-id
      Description: Facebook Page ID to Post Stories

  # Systems Manager Parameter for Facebook Access Token
  FacebookAccessTokenSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlive2fbstories/facebook/access_token
      Type: SecureString
      Value: dummy-access-token
      Description: Facebook Graph API Long-Lived Access Token

  # Systems Manager Parameter for YouTube Channel ID
  YouTubeChannelIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlive2fbstories/youtube/channel_id
      Type: String
      Value: default-channel-id
      Description: YouTube Channel ID to Monitor for Live Streams

  # Systems Manager Parameter for YouTube Data API Key
  YouTubeApiKeySSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlive2fbstories/youtube/api_key
      Type: SecureString
      Value: dummy-api-key
      Description: YouTube Data API Key

  # Systems Manager Parameter for WebSub Callback URL
  WebSubCallbackUrlSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlive2fbstories/websub/callback_url
      Type: String
      Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/webhook
      Description: WebSub Callback URL for PubSubHubbub Notifications
